[package]
name = "highs"
version = "2.4.0"
authors = ["Ophir LOJKINE", "rust-or"]
edition = "2021"
description = "Safe rust bindings for the HiGHS linear programming solver. See http://highs.dev."
license = "MIT"
repository = "https://github.com/rust-or/highs"
keywords = ["linear-programming", "optimization", "math", "solver"]

[dependencies]
highs-sys = { git = "https://github.com/oaasis-ai/highs-sys.git", rev = "d309728550c1dd32aa6e0bddeb669e4224208911", features = ["hipo"] }
log = "0.4.27"
