[package]
name = "highs"
version = "2.4.0"
authors = ["Ophir LOJKINE", "rust-or"]
edition = "2021"
description = "Safe rust bindings for the HiGHS linear programming solver. See http://highs.dev."
license = "MIT"
repository = "https://github.com/rust-or/highs"
keywords = ["linear-programming", "optimization", "math", "solver"]

[dependencies]
highs-sys = { git = "https://github.com/oaasis-ai/highs-sys.git", rev = "9a731e27a465c3ba91e33861d49cdf57f6411ffc", features = ["hipo"] }
log = "0.4.27"
