[package]
name = "highs"
version = "2.4.0"
authors = ["Ophir LOJKINE", "rust-or"]
edition = "2021"
description = "Safe rust bindings for the HiGHS linear programming solver. See http://highs.dev."
license = "MIT"
repository = "https://github.com/rust-or/highs"
keywords = ["linear-programming", "optimization", "math", "solver"]

[dependencies]
highs-sys = { git = "https://github.com/oaasis-ai/highs-sys.git", rev = "f509c2ecf301b20bc150eb7ba1a2a671eb069f7b", features = ["hipo"] }
log = "0.4.27"
